blueprint:
  name: 🌅 Luci Giardino Intelligenti
  description: >
    Blueprint avanzato per la gestione automatica delle luci del giardino.
    
    Caratteristiche:
    • Accensione automatica al tramonto (elevazione sole configurabile)
    • Aumento luminosità con rilevamento movimento
    • Spegnimento programmato notturno
    • Completamente personalizzabile via UI
    
    Perfetto per illuminazione esterna intelligente e risparmio energetico.
  
  domain: automation
  author: Il Tuo Nome
  homeassistant:
    min_version: 2023.4.0
  
  input:
    # LUCI E SENSORI
    garden_lights:
      name: 🔆 Luci del Giardino
      description: Seleziona le luci del giardino da controllare automaticamente
      selector:
        target:
          entity:
            domain: light
    
    motion_sensor:
      name: 🚶 Sensore di Movimento
      description: Sensore PIR o di movimento per attivazione luci (opzionale)
      default: {}
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    
    # CONFIGURAZIONE SOLE
    sun_elevation:
      name: 🌅 Elevazione Sole per Accensione
      description: Gradi sotto l'orizzonte per accensione automatica (-6° = tramonto civile)
      default: -6
      selector:
        number:
          min: -15
          max: 0
          step: 0.5
          unit_of_measurement: "°"
    
    # LUMINOSITÀ
    base_brightness:
      name: 💡 Luminosità Base (Serale)
      description: Intensità delle luci durante le ore serali
      default: 30
      selector:
        number:
          min: 10
          max: 100
          step: 5
          unit_of_measurement: "%"
    
    motion_brightness:
      name: 🔆 Luminosità con Movimento
      description: Intensità quando viene rilevato movimento
      default: 80
      selector:
        number:
          min: 50
          max: 100
          step: 5
          unit_of_measurement: "%"
    
    # TIMING
    motion_duration:
      name: ⏱️ Durata Luminosità Alta
      description: Tempo di mantenimento alta intensità dopo movimento
      default:
        minutes: 5
      selector:
        duration:
          enable_day: false
    
    night_off_time:
      name: 🌙 Orario Spegnimento Notturno
      description: Ora di spegnimento automatico delle luci
      default: "23:30:00"
      selector:
        time:
    
    # OPZIONI AVANZATE
    weekday_only:
      name: 📅 Solo Giorni Feriali
      description: Attiva automazione solo da lunedì a venerdì
      default: false
      selector:
        boolean:
    
    enable_weather_boost:
      name: 🌧️ Aumento per Maltempo
      description: Aumenta luminosità base quando piove/c'è nebbia (+20%)
      default: false
      selector:
        boolean:

# VARIABILI GLOBALI
variables:
  motion_entity: !input motion_sensor
  has_motion_sensor: "{{ motion_entity != none and motion_entity != '' }}"
  weekday_only: !input weekday_only
  is_weekday: "{{ now().weekday() < 5 }}"
  should_run: "{{ not weekday_only or is_weekday }}"
  base_brightness: !input base_brightness
  weather_boost: !input enable_weather_boost
  weather_condition: "{{ states('weather.home') if weather_boost else 'clear' }}"
  final_base_brightness: >
    {% if weather_boost and weather_condition in ['rainy', 'snowy', 'fog', 'cloudy'] %}
      {{ [base_brightness + 20, 100] | min }}
    {% else %}
      {{ base_brightness }}
    {% endif %}

# TRIGGER MULTIPLI
trigger:
  # 1. Tramonto - Accensione automatica
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: !input sun_elevation
    id: sunset_trigger
  
  # 2. Movimento rilevato - Aumento luminosità
  - platform: state
    entity_id: !input motion_sensor
    to: 'on'
    id: motion_on_trigger
  
  # 3. Fine movimento - Timer scaduto
  - platform: state
    entity_id: !input motion_sensor
    to: 'off'
    for: !input motion_duration
    id: motion_off_trigger
  
  # 4. Spegnimento notturno programmato
  - platform: time
    at: !input night_off_time
    id: night_off_trigger
  
  # 5. Riaccensione dopo spegnimento notturno (se ancora buio)
  - platform: time
    at: "06:00:00"
    id: morning_check_trigger

# CONDIZIONI GLOBALI
condition:
  - condition: template
    value_template: "{{ should_run }}"

# AZIONI PRINCIPALI
action:
  # SCELTA AZIONE BASATA SUL TRIGGER
  - choose:
    
    # === TRAMONTO: ACCENSIONE LUCI ===
    - conditions:
        - condition: trigger
          id: sunset_trigger
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: !input sun_elevation
      sequence:
        - service: light.turn_on
          target: !input garden_lights
          data:
            brightness_pct: "{{ final_base_brightness }}"
            transition: 30
        - service: logbook.log
          data:
            name: "🌅 Luci Giardino"
            message: "Accese automaticamente al tramonto ({{ final_base_brightness }}%)"
    
    # === MOVIMENTO RILEVATO ===
    - conditions:
        - condition: trigger
          id: motion_on_trigger
        - condition: template
          value_template: "{{ has_motion_sensor }}"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: !input sun_elevation
        - condition: time
          before: !input night_off_time
      sequence:
        - service: light.turn_on
          target: !input garden_lights
          data:
            brightness_pct: !input motion_brightness
            transition: 2
        - service: logbook.log
          data:
            name: "🚶 Movimento Rilevato"
            message: "Luci aumentate al {{ motion_brightness }}%"
    
    # === FINE MOVIMENTO ===
    - conditions:
        - condition: trigger
          id: motion_off_trigger
        - condition: template
          value_template: "{{ has_motion_sensor }}"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: !input sun_elevation
        - condition: time
          before: !input night_off_time
      sequence:
        - service: light.turn_on
          target: !input garden_lights
          data:
            brightness_pct: "{{ final_base_brightness }}"
            transition: 10
        - service: logbook.log
          data:
            name: "⏱️ Timer Movimento"
            message: "Luci ridotte al {{ final_base_brightness }}% dopo {{ motion_duration }}"
    
    # === SPEGNIMENTO NOTTURNO ===
    - conditions:
        - condition: trigger
          id: night_off_trigger
      sequence:
        - service: light.turn_off
          target: !input garden_lights
          data:
            transition: 30
        - service: logbook.log
          data:
            name: "🌙 Spegnimento Notturno"
            message: "Luci spente automaticamente alle {{ night_off_time }}"
    
    # === CONTROLLO MATTUTINO ===
    - conditions:
        - condition: trigger
          id: morning_check_trigger
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: !input sun_elevation
      sequence:
        - service: light.turn_on
          target: !input garden_lights
          data:
            brightness_pct: "{{ final_base_brightness }}"
            transition: 30
        - service: logbook.log
          data:
            name: "🌅 Controllo Mattutino"  
            message: "Luci riaccese - ancora buio alle 06:00"

# MODALITÀ: SINGLE per evitare sovrapposizioni
mode: single
max_exceeded: silent