blueprint:
  name: 🌅 Luci Giardino Intelligenti (con Frigate)
  description: >
    Blueprint per la gestione delle luci del giardino, ottimizzato per sensori di presenza persona di Frigate.
    Include controllo per giorni lavorativi, boost meteo e transizioni morbide.
  domain: automation
  author: Matte1240
  homeassistant:
    min_version: 2023.4.0

  input:
    garden_lights:
      name: 🔆 Luci del Giardino
      description: Seleziona le luci del giardino da controllare automaticamente.
      selector:
        target:
          entity:
            domain: light

    frigate_person_sensor:
      name: 🚶 Sensore Persona Frigate (opzionale)
      description: "Sensore binario di Frigate che rileva una persona (es. binary_sensor.camera_person_motion). Lascia vuoto se non disponibile."
      default: null
      selector:
        entity:
          domain: binary_sensor

    sun_elevation:
      name: 🌅 Elevazione Sole per Accensione
      description: Gradi sotto l'orizzonte per accensione automatica (-6 = tramonto civile).
      default: -6
      selector:
        number:
          min: -15
          max: 0
          step: 0.5
          unit_of_measurement: "°"

    base_brightness:
      name: 💡 Luminosità Base (Serale %)
      default: 30
      selector:
        number:
          min: 10
          max: 100
          step: 5
          unit_of_measurement: "%"

    person_brightness:
      name: 🔆 Luminosità con Persona Rilevata (%)
      default: 80
      selector:
        number:
          min: 50
          max: 100
          step: 5
          unit_of_measurement: "%"

    person_timeout:
      name: ⏱️ Timeout Assenza Persona
      description: Tempo di attesa dopo che la persona non è più rilevata prima di tornare alla luminosità base.
      default:
        minutes: 5
      selector:
        duration:
          enable_day: false

    night_off_time:
      name: 🌙 Orario Spegnimento Notturno
      default: "23:30:00"
      selector:
        time: {}

    weekday_only:
      name: 📅 Solo Giorni Feriali
      default: false
      selector:
        boolean: {}

    enable_weather_boost:
      name: 🌧️ Aumento per Maltempo
      description: Aumenta luminosità base quando c'è maltempo (+20%).
      default: false
      selector:
        boolean: {}

variables:
  person_entity: !input frigate_person_sensor
  has_person_sensor: "{{ person_entity not in [none, '', 'unknown'] }}"
  weekday_only: !input weekday_only
  is_weekday: "{{ now().weekday() < 5 }}"
  should_run: "{{ not weekday_only or is_weekday }}"
  base_brightness_in: !input base_brightness
  weather_boost_enabled: !input enable_weather_boost
  weather_state: "{{ states('weather.home') | default('unknown', true) }}"
  final_base_brightness: >
    {% set b = base_brightness_in | int(0) %}
    {% if weather_boost_enabled and weather_state in ['rainy','snowy','fog','cloudy','rain'] %}
      {{ [b + 20, 100] | min }}
    {% else %}
      {{ b }}
    {% endif %}

trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: !input sun_elevation
    id: sunset_trigger

  # Trigger di presenza persona basato su template per gestire il sensore opzionale
  - platform: template
    value_template: "{{ has_person_sensor and is_state(person_entity, 'on') }}"
    id: person_on_trigger

  - platform: template
    value_template: "{{ has_person_sensor and is_state(person_entity, 'off') }}"
    for: !input person_timeout
    id: person_off_trigger

  - platform: time
    at: !input night_off_time
    id: night_off_trigger

  - platform: time
    at: "06:00:00"
    id: morning_check_trigger

condition:
  - condition: template
    value_template: "{{ should_run }}"

action:
  - choose:
      # TRAMONTO / CONTROLLO MATTUTINO
      - conditions:
          - condition: trigger
            id:
              - sunset_trigger
              - morning_check_trigger
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: !input sun_elevation
        sequence:
          - service: light.turn_on
            target: !input garden_lights
            data:
              brightness_pct: "{{ final_base_brightness }}"
              transition: 30
          - service: logbook.log
            data:
              name: "🌅 Luci Giardino"
              message: "Accese ({{ trigger.id }}) — Luminosità: {{ final_base_brightness }}%"

      # PERSONA RILEVATA
      - conditions:
          - condition: trigger
            id: person_on_trigger
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: !input sun_elevation
        sequence:
          - service: light.turn_on
            target: !input garden_lights
            data:
              brightness_pct: !input person_brightness
              transition: 2
          - service: logbook.log
            data:
              name: "🚶 Persona Rilevata"
              message: "Luminosità aumentata a {{ !input person_brightness }}%"

      # FINE PRESENZA PERSONA
      - conditions:
          - condition: trigger
            id: person_off_trigger
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: !input sun_elevation
        sequence:
          - service: light.turn_on
            target: !input garden_lights
            data:
              brightness_pct: "{{ final_base_brightness }}"
              transition: 10
          - service: logbook.log
            data:
              name: "⏱️ Persona non più rilevata"
              message: "Ripristinata luminosità a {{ final_base_brightness }}%"

      # SPEGNIMENTO NOTTURNO
      - conditions:
          - condition: trigger
            id: night_off_trigger
        sequence:
          - service: light.turn_off
            target: !input garden_lights
            data:
              transition: 30
          - service: logbook.log
            data:
              name: "🌙 Spegnimento Notturno"
              message: "Luci spente come da programma ({{ !input night_off_time }})"
    default: []

mode: restart
max_exceeded: silent