blueprint:
  name: 🌅 Luci Giardino Intelligenti (corretto)
  description: >
    Blueprint migliorato per la gestione automatica delle luci del giardino.
    Optional motion sensor, controllo per giorni lavorativi, boost meteo e
    transizioni morbide.
  domain: automation
  author: Matte1240
  homeassistant:
    min_version: 2023.4.0

  input:
    garden_lights:
      name: 🔆 Luci del Giardino
      description: Seleziona le luci del giardino da controllare automaticamente
      selector:
        target:
          entity:
            domain: light

    motion_sensor:
      name: 🚶 Sensore di Movimento (opzionale)
      description: Sensore PIR o di movimento. Lascia vuoto se non disponibile.
      default: null
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    sun_elevation:
      name: 🌅 Elevazione Sole per Accensione
      description: Gradi sotto l'orizzonte per accensione automatica (-6 = tramonto civile)
      default: -6
      selector:
        number:
          min: -15
          max: 0
          step: 0.5
          unit_of_measurement: "°"

    base_brightness:
      name: 💡 Luminosità Base (Serale %)
      default: 30
      selector:
        number:
          min: 10
          max: 100
          step: 5
          unit_of_measurement: "%"

    motion_brightness:
      name: 🔆 Luminosità con Movimento (%)
      default: 80
      selector:
        number:
          min: 50
          max: 100
          step: 5
          unit_of_measurement: "%"

    motion_duration:
      name: ⏱️ Durata Luminosità Alta
      default:
        minutes: 5
      selector:
        duration:
          enable_day: false

    night_off_time:
      name: 🌙 Orario Spegnimento Notturno
      default: "23:30:00"
      selector:
        time: {}

    weekday_only:
      name: 📅 Solo Giorni Feriali
      default: false
      selector:
        boolean: {}

    enable_weather_boost:
      name: 🌧️ Aumento per Maltempo
      description: Aumenta luminosità base quando c'è maltempo (+20%)
      default: false
      selector:
        boolean: {}

variables:
  motion_entity: !input motion_sensor
  has_motion_sensor: "{{ motion_entity not in [None, '', 'unknown'] }}"
  weekday_only: !input weekday_only
  is_weekday: "{{ now().weekday() < 5 }}"
  should_run: "{{ (not weekday_only) or is_weekday }}"
  base_brightness_in: !input base_brightness
  weather_boost_enabled: !input enable_weather_boost
  # safe weather state retrieval
  weather_state: "{{ states('weather.home') | default('unknown') }}"
  final_base_brightness: >
    {% set b = base_brightness_in | int %}
    {% if weather_boost_enabled and weather_state in ['rainy','snowy','fog','cloudy','rain'] %}
      {{ [b + 20, 100] | min }}
    {% else %}
      {{ b }}
    {% endif %}

trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: !input sun_elevation
    id: sunset_trigger

  # movimento: attivato solo se fornito (se non fornito ignoreremo azioni via condizioni)
  - platform: state
    entity_id: !input motion_sensor
    to: 'on'
    id: motion_on_trigger

  - platform: state
    entity_id: !input motion_sensor
    to: 'off'
    for: !input motion_duration
    id: motion_off_trigger

  - platform: time
    at: !input night_off_time
    id: night_off_trigger

  - platform: time
    at: "06:00:00"
    id: morning_check_trigger

condition:
  - condition: template
    # controllo centrale: rispetta l'opzione giorni lavorativi
    value_template: "{{ should_run }}"

action:
  - choose:
      # TRAMONTO: accendi con luminosità base
      - conditions:
          - condition: trigger
            id: sunset_trigger
        sequence:
          - service: light.turn_on
            target: !input garden_lights
            data:
              brightness_pct: "{{ final_base_brightness }}"
              transition: 30
          - service: logbook.log
            data:
              name: "🌅 Luci Giardino"
              message: "Accese al tramonto — {{ final_base_brightness }}%"

      # MOVIMENTO: aumenta luminosità (solo se sensore configurato e buio)
      - conditions:
          - condition: template
            value_template: "{{ has_motion_sensor }}"
          - condition: trigger
            id: motion_on_trigger
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: !input sun_elevation
        sequence:
          - service: light.turn_on
            target: !input garden_lights
            data:
              brightness_pct: !input motion_brightness
              transition: 2
          - service: logbook.log
            data:
              name: "🚶 Movimento"
              message: "Luminosità aumentata a {{ !input motion_brightness }}%"

      # FINE MOVIMENTO: ritorna a base (solo se sensore configurato)
      - conditions:
          - condition: template
            value_template: "{{ has_motion_sensor }}"
          - condition: trigger
            id: motion_off_trigger
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: !input sun_elevation
        sequence:
          - service: light.turn_on
            target: !input garden_lights
            data:
              brightness_pct: "{{ final_base_brightness }}"
              transition: 10
          - service: logbook.log
            data:
              name: "⏱️ Movimento Terminato"
              message: "Ripristinata luminosità a {{ final_base_brightness }}%"

      # SPEGNIMENTO NOTTURNO programmato
      - conditions:
          - condition: trigger
            id: night_off_trigger
        sequence:
          - service: light.turn_off
            target: !input garden_lights
            data:
              transition: 30
          - service: logbook.log
            data:
              name: "🌙 Spegnimento Notturno"
              message: "Luci spente alle {{ !input night_off_time }}"

      # CONTROLLO MATTUTINO alle 06:00 (riaccendi se ancora buio)
      - conditions:
          - condition: trigger
            id: morning_check_trigger
          - condition: numeric_state
            entity_id: sun.sun
            attribute: elevation
            below: !input sun_elevation
        sequence:
          - service: light.turn_on
            target: !input garden_lights
            data:
              brightness_pct: "{{ final_base_brightness }}"
              transition: 30
          - service: logbook.log
            data:
              name: "🌅 Controllo Mattutino"
              message: "Luci riaccese alle 06:00 — ancora buio ({{ final_base_brightness }}%)"
    # Se nessun trigger corrisponde, non viene eseguita nessuna azione.
    # Questo è il comportamento atteso.
    default: []

mode: restart